name: maecg
channels:
  - defaults
dependencies:
  - python=3.10.9
  - pip
  - pip:
    - numpy
    - torch
    - torchvision
    - timm
    - wfdb
    - neurokit2
    - tqdm
    - seaborn
    - tensorboard
